{% set name = "pytest-cookies" %}
{% set version = "0.5.1" %}
{% set sha256 = "b33f7f51772444b9b25991c4eeaea74a69dc9a6e08b09596b9574548a8812f34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  preserve_egg_dir: true

requirements:
  host:
    - python
    - pip

  run:
    - arrow <0.14.0
    - python
    - pytest >=3.3.0,<6.0.0
    - cookiecutter >=1.4.0,<=1.6.0

test:
  imports:
    - pytest_cookies

about:
  home: https://github.com/hackebrot/pytest-cookies
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Pytest plugin for your Cookiecutter templates

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
