{% set name = "pytest-cookies" %}
{% set version = "0.6.1" %}
{% set sha256 = "94c41ad914d420b57bc31d58ab2c0b103322c11d07d13b8d245c85fa9b069714" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python >=3.6
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  preserve_egg_dir: true

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - cookiecutter >=1.4.0
    - pytest >=3.3.0
    - python >=3.6

test:
  imports:
    - pytest_cookies

about:
  home: https://github.com/hackebrot/pytest-cookies
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Pytest plugin for your Cookiecutter templates

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
