travis:
  secure:
    BINSTAR_TOKEN: sEK03pfafPUBxVclcOqSpjwPXkPpgYVUxC1S7Wjte7K9V1erHJEUulmtDfaFwLr5z+kdVMyLz3z6Jccv0D8oxjPj5UstXOpc1yOPRCuhkoDGZQAxn5oItT6v9fHkHg4v0xPtTl8vcVVsReTxSVw4lXZ0vgT0aOgBFlhsBb0dfdaD+qJ9NzqU9rlK1wg7cDwMtta2HvGXzrEYSeXHoVVoV9xmSFoixZUluNU/vCcZgOmEsxEj2kRLnj3QULOo+zNK5yU2w8hcYUqBTVypGdRYVgNjD++54SyFqxErApLJBLa/lCBMZxqcMTN7wOZiVAV+J1mjnp/iXNeZXZO4naHcpInvpeNtsOI9p6AXR7qmDz9McY8tKJ+xu0YwuJBOghw2YXOHKKJ8QtFUjW8AhipZWCJrZoExIpiyeo8PtXh1qg7fsBr4GFKQx1HgYAjaQNd0r4PQq/pHO5cKgh3K91IThGpsqeB679GmnNdSBBRZpnEKZCvEbxthg41uwic0UBUGf1D68EX6KyHWavWmSCD7Z3JsFbcr10BlF4h15SflaQ0vzcy5kJnRmy35QCjGwVwp/lVZQGP0c2bidoL0dEUnHHlR6dx4A+j6QoNLHdCpu3KagNk4b2qmzBmur2kBpYL8DzWt07GW17cGzotIO8Lwttj6zwi2PNLuDKM29hNDlZk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
